### ISSUE TITLE
Website's down

### ISSUE THREAD

**Issue by virejdasani** [xnbox/DeepfakeHTTP#1]
The website returns a 404

**Comment by xnbox** [comment]
If the request is not found in the dump status 400 (not 404) will be returned. It's very strange... Are you sure that you run DeepfakeHTTP and not another server on localhost:8080? Please provide your command line and dump file.

**Comment by virejdasani** [comment]
My bad for not mentioning this. https://xnbox.github.io/DeepfakeHTTP <-- this website is down

**Comment by xnbox** [comment]
Oh, I see. Thanks!

**Comment by xnbox** [comment]
The issue is related to Github project website. Fixed.
