### ISSUE TITLE
POST request with Content-Type: application/json

### ISSUE THREAD

**Issue by mjablecnik** [xnbox/DeepfakeHTTP#10]
Can you show me example how to fake POST request with `Content-Type: application/json`?
For this curl?:
```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"username":"xyz","password":"xyz"}' \
  http://localhost:3000/api/login
```
response can be also `Content-Type: application/json`
for example:
{
    "name": "Martin",
    "surname: "Jablecnik",
    "logged_in: true
}

In your examples I see only GET for `Content-Type: application/json` and POST for `Content-Type: application/x-www-form-urlencoded`

Thank you very much.

**Comment by xnbox** [comment]
POST /aaa HTTP/1.1
Content-Type: application/json

HTTP/1.1 200 OK
Content-Type: application/json

{"username":"xyz","password":"xyz"}

**Comment by xnbox** [comment]
Works for me.
If you have trouble with it, please send me as an attachment your example.

**Comment by mjablecnik** [comment]
Yes.
```

POST /aaa HTTP/1.1
Content-Type: application/json

{"username":"xyz","password":"xyz"}

HTTP/1.1 200 OK
Content-Type: application/json

{
    "name":"Martin",
    "surname":"Jablecnik"
}
```
Works for me also right now.

My previous experiment was similar to:
```
POST /aaa HTTP/1.1
Content-Type: application/json

{
    "username":"xyz",
    "password":"xyz"
}

HTTP/1.1 200 OK
Content-Type: application/json

{
    "name":"Martin",
    "surname":"Jablecnik"
}
```
Where request body have a little different format of body so it didn't work because the json `--data` wasn't exactly same. Isn't true?

**Comment by xnbox** [comment]
You're absolutely right. If there is a difference in the first line of the query, headers, or body, the status will be given: 400 Bad Request.
To get the query to pass, you need to remove from the dump what does not match the real query.
Wildcards (*, ?) are allowed in query path and headers. This gives some flexibility.

**Comment by xnbox** [comment]
Sorry! Wildcards are allowed in query parameters values.
In path you can use OpenAPI styled parameters: <code>GET /customers/{country}/{id}/info HTTP/1.1</code>

**Comment by mjablecnik** [comment]
Yes ok. Now my question is: Can the request body of `Content-Type: application/json` be parsed and compared by keys and values instead of all body?
Because json:
```
{
    "username":"xyz",
    "password":"xyz"
}
```
and json:
```
{"username":"xyz", "password":"xyz"}
```
are same. Different is only format and indentation.

This should be useful because when I have:
```
{"username":"xyz", "password":"xyz"}
```
and
```
{"username":"xyz","password":"xyz"}
```
So finding difference and why it doesn't work can be very hard because diff is in only one small space..

**Comment by xnbox** [comment]
I understand where this concept comes from. In terms of JSON semantics, the samples given are identical. But the purposes of comparing dumps may be different. Perhaps someone just wants to know that the server response has not changed. Or someone can just snatch JSON data with <code>substring()</code>. I don't think this is good practice, but in the interest of increasing performance, why not?
