### ISSUE TITLE
Comments behind of text

### ISSUE THREAD

**Issue by mjablecnik** [xnbox/DeepfakeHTTP#11]
It would be nice to have also comments starting in the middle of line after some text.

For example I can have this endpoint:
```
#
# Login endpoint
#
POST /login HTTP/1.1
Content-Type: application/json

{"username":"xyz","password":"xyz"}

HTTP/1.1 200 OK
Content-Type: application/json

{
    "name":"Martin",          # here is user name
    "surname":"Jablecnik"     # here is user surname
}
```
where I have to comment my fields of output body but I don't want to have it in the real output:

![image](https://user-images.githubusercontent.com/2686906/133310387-1ccbcd09-a6c6-402b-a798-35ec9ae9fa04.png)

**Comment by xnbox** [comment]
To be honest, I was thinking about something like that, but there's a problem here - by allowing comments like that, we're injecting them into the request body. How do we have to filter out these comments before sending them? And what to do if we send HTML or PDF?... Or even arbitrary text with Content-Type: text/plain?...
PDF example:

```
#
# Response with PDF file
#
GET /my.pdf HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/pdf
X-Body-Type: application/pdf

%PDF-1.4
1 0 obj
<<
	/Length 51
>>
stream
1 0 0 RG
5 w
36 144 m
180 144 l
180 36 l
36 36 l
s
endstream
endobj
2 0 obj
<<
	/Type /Catalog
	/Pages 3 0 R
>>
endobj
3 0 obj
<<
	/Type /Pages
	/Kids [4 0 R ]
	/Count 1
>>
endobj
4 0 obj
<< 
	/Type /Page
	/Parent 3 0 R
	/MediaBox [0 0 612 792] 
	/Contents 1 0 R
>>
endobj


xref
0 4
0000000000 65535 f
0000000010 00000 n
0000000113 00000 n
0000000165 00000 n
0000000227 00000 n
trailer 
<<
	/Size 4 
	/Root 2 0 R
>>
startxref
344
%%EOF
```

**Comment by mjablecnik** [comment]
Yes it make sense.
So when the comment is inside of the body it can be escaped by some character similar like in programming languages for escaping special character in strings..
Something like this can be solution of the problem:

```
#
# Login endpoint
#
POST /login HTTP/1.1
Content-Type: application/json

{"username":"xyz","password":"xyz"}

HTTP/1.1 200 OK
Content-Type: application/json

{
    "name":"Martin",          \# here is user name
    "surname":"Jablecnik"     \# here is user surname
}
```

Or maybe add header `X-Enable-Comments: True` can be also good solution.
Default will be false and when I will want to enable it for my purpose so I will add there it.

**Comment by xnbox** [comment]
I think it's almost impossible in this form.Take YAML, for example - it has its own comment character # and its own escape character.
The only solution I can think of is to set the width of the body rows in characters <code>X-Body-Row-Length: 40</code>. Everything to the right of the dump should be ignored.

**Comment by mjablecnik** [comment]
Yes I am also thinking about it that I will use some different file format then only this text dumps..
Can you show me some small example of the yaml file for DeepfakeHTTP? 
I didn't see it in your examples.

**Comment by xnbox** [comment]
I didn't impose YAML on you. I just wanted to show you that in case you want to use it, it will be very difficult to recognize where the native YAML comments are and where the dump ones are.
I don't have an example with YAML, but you shouldn't have a problem with YAML.

**Comment by xnbox** [comment]
I just thought that for your purposes
would work fine <code>X-Body-Type: text/template</code>
See example:

```
#
# Comments example
#
GET /customer2.json HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json
X-Body-Type: text/template

<#-- Put your comments anywhere on body -->
<#-- Customer record -->
{
    "id": 123,
    "fname": "John", <#-- First Name -->
    "lname": <#-- ...even here --> "Doe",
    "email": ["john@example.com", "johndoe@example.com"]
}
<#-- ...and here -->
.
```
