### ISSUE TITLE
How to configure https to work?

### ISSUE THREAD

**Issue by LuccaPrado** [xnbox/DeepfakeHTTP#3]
Hi! When I start the project, I have an notice saying that "The Apache Tomcat Native library which allows using OpenSSL was not found on the java." This is no problem for me (it's a little bit anoying that it prints mt entire path after that, but no problem)

But the real problem is when I try to point to my dfHttp as if it used https, so using "https://localhost:8080" instead of "http://localhost:8080" when this happens, it print an error and a stacktrace. I guess that this is not so intuitive for who is using
![image](https://user-images.githubusercontent.com/8813731/132876590-a7626fa9-e044-494f-9b6e-c867d95e554c.png)

**Comment by xnbox** [comment]
Hi!

Thank you for the feedback!
I should probably improve the documentation.

By default, the server uses http and port 8080.
If you need to configure work via https, then first of all I want to note that DeepfakeHTTP has an Apache Tomcat web server under the hood, so any protocol configuration questions are standard Apache Tomcat configuration questions.

**How to configure https to work?**

1. Create keystore:
```
keytool -genkeypair -alias cert -keyalg RSA -keysize 2048 -sigalg SHA256withRSA -keypass 123456 -storepass 123456 -keystore /home/john/localhost-rsa.jks
```

2. Open <code>df.jar</code> in any ZIP management tool.

3. Find the file:
<code>META-INF/tomcat/conf/server.xml</code> (this is a standard, unchanged file from the Tomcat distribution)

4. Comment out the entry in this file:
```xml
<!--
    <Connector port = "8080" protocol = "HTTP/1.1"
               connectionTimeout = "20000"
               redirectPort = "8443" />
-->
```

4. Add new entry:
```xml
    <Connector port = "8443" protocol = "org.apache.coyote.http11.Http11NioProtocol"
               maxThreads = "150" SSLEnabled = "true">
        <UpgradeProtocol className = "org.apache.coyote.http2.Http2Protocol" />
        <SSLHostConfig>

            <Certificate certificateKeystoreFile = "/home/john/localhost-rsa.jks"
                         certificateKeystorePassword = "123456"
                         type = "RSA" />
        </SSLHostConfig>
    </Connector>
```
5. Сlose the ZIP manager and make sure all changes are saved in the <code>df.jar</code> file.
6. Restart the server.
7. Use a browser to check whether the server is running: [https://localhost:8843](https://localhost:8843)

See: [https://tomcat.apache.org/tomcat-10.0-doc/ssl-howto.html](https://tomcat.apache.org/tomcat-10.0-doc/ssl-howto.html) for more info.

**Comment by LuccaPrado** [comment]
Thanks!!! This will be useful for others too!

**Comment by xnbox** [comment]
Please see **v1.0.7** for better SSL support
