### ISSUE TITLE
Trim blank lines of response

### ISSUE THREAD

**Issue by mjablecnik** [xnbox/DeepfakeHTTP#6]
My responses have some blank lines on end of every response:
![image](https://user-images.githubusercontent.com/2686906/133200724-865f40e5-d3c7-4e13-bc2f-7a405d3cee26.png)

Blank lines should be trim before send of response.

**Comment by xnbox** [comment]
- I purposely keep the original response content.
Sometimes people want to compare the responses received from the test server and the real one byte for byte.
- If you do not leave trailing lines in the dump, they will not be in the response.
- I'm thinking of making a CLI option that allows you to trim/save empty lines? What do you think about that?
Thank you!

P.S. Apart from that, I noticed now, that in any case, the original response is augmented with an extra line break. This needs to be fixed.

**Comment by xnbox** [comment]
>Apart from that, I noticed now, that in any case, the original response is augmented with an extra line break. This needs to be fixed.

I fixed this bug.

**Comment by mjablecnik** [comment]
I have this file:
```
#-----

GET /dapi/v1/user HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json

{
    "firstName": "Martin",
    "id": 67,
    "lastName": "Jablecnik",
    "username": "ML7920161687"
} 

#-----

GET /dapi/v1/user/error HTTP/1.1

HTTP/1.1 403 OK
Content-Type: application/json

{
    "args": [
        "16e9a3583dbd01d7fca1a3db62d2fe"
    ],
    "key": "Unknown device %s",
    "message": "Unknown device 16e9a3583dbd01d7fca1a3db62d2fe"
}

#-----

POST /dapi/v1/device/register HTTP/1.1

HTTP/1.1 204 OK
Content-Type: application/json

#-----
```

Which I want to continually edit and add new endpoints.
I added simple `#-----` line as delimiter between endpoints for better readability and known where some endpoint starts and where is end.
I don't know if exists some better way or format but if you add something how to write endpoints without spaces as delimiters it should be nice..

CLI option can be good but my personal opinion is that trimming of blank lines should be default behavior and CLI flag will disable/enable it.

**Comment by xnbox** [comment]
Thank you for the feedback!

>CLI option can be good but my personal opinion is that trimming of blank lines should be default behavior and CLI flag will disable/enable it.

OK

>...how to write endpoints without spaces as delimiters it should be nice...

Blank lines are **not delimiters** and can be used to improve readability.
- Blank lines, as well as comments <code>#</code>, are ignored when parsing (unless, of course, they are part of the request/response body).
- One empty line between headers and body is required by the HTTP protocol.

>I added simple #----- line as a delimiter between endpoints...

I do almost the same:
```text
# -----------------------------------------------------------------------------------------
#
# Start DeepfakeHTTP web server with examples from command line:
#
# java -jar df.jar --openapi-path /api --openapi-title 'DeepfakeHTTP Examples' examples.txt
#
# Use a browser to check whether the server is running:
# http://localhost:8080
#
# Get built-in OpenAPI client:
# http://localhost:8080/api
#
# -----------------------------------------------------------------------------------------


#
# Hello, World!
#
GET / HTTP/1.1
X-OpenAPI-Summary: Hello, World!
X-OpenAPI-Description: Hello, World! example
X-OpenAPI-Tags: Basic usage, HTML

HTTP/1.1 200 OK
Content-Type: text/html

<!DOCTYPE html>
<html lang="en">
<body>
	<h1>Hello, World!</h1>
</body>
</html>

#
# favicon
#
GET /favicon.ico HTTP/1.1
X-OpenAPI-Summary: Favicon
X-OpenAPI-Description: Provide favicon.ico file
X-OpenAPI-Tags: Basic usage, File generation, Images

HTTP/1.1 200 OK
X-Body-Type: text/uri-list

data:image/vnd.microsoft.icon;base64,AAABAAEAEBAAAAEAGABoAwAAFgAAACgAAAAQAAAAIAAAAAEAGAAAAAAAAAMAABILAAASCwAAAAAAAAAAAAASVuwSVuwSVuwSVuwAif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8SVuwSVuwSVuwSVuwSVuwSVuwAif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8SVuwSVuwSVuwAif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8SVuwSVuwAif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8SVuwAif8Aif8Aif8Aif8Aif8AAwYAAwYAAwYAAwYAAwYAAwYAif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8AAwYAAwYAif8Aif8Aif8Aif8AAwYAAwYAif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8AAwYAif8AAwYAAwYAif8Aif8Aif8AAwYAAwYAif8Aif8AAwYAif8Aif8Aif8Aif8Aif8AAwYAAwYAif8Aif8Aif8Aif8Aif8AAwYAAwYAAwYAif8Aif8Aif8SVuwAif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8SVuwSVuwAif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8SVuwSVuwSVuwAif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8SVuwSVuwSVuwSVuwSVuwSVuwAif8Aif8Aif8Aif8Aif8Aif8Aif8Aif8SVuwSVuwSVuwSVuzwDwAAwAMAAIABAACAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAAgAEAAMADAADwDwAA


#
# Simple Form (1)
#
GET /form1.html HTTP/1.1

HTTP/1.1 200 OK

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Form Example</title>
</head>
<body>
<form action="/action_page.php" method="POST">
  <label for="fname">First name:</label>
  <input type="text" id="fname" name="fname"><br><br>
  <label for="lname">Last name:</label>
  <input type="text" id="lname" name="lname"><br><br>
  <input type="submit" value="Submit">
</form></body>
</html>


#
# Action for simple form (1) processing
#
POST /action_page.php HTTP/1.1

HTTP/1.1 200 OK
Content-Type: text/html
X-Body-Type: text/template

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Form Example</title>
</head>
<body>
	<h1>Hello, ${fname[0]} ${lname[0]}</h1>
</body>
</html>


#
# Simple Form (2)
#
GET /form2.html HTTP/1.1

HTTP/1.1 200 OK

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Form Example</title>
</head>
<body>
<form action="/action_page2.php" method="POST">
  <label for="fname">First name:</label>
  <input type="text" id="fname" name="fname" value="John"><br><br>
  <label for="lname">Last name:</label>
  <input type="text" id="lname" name="lname" value="Doe"><br><br>
  <input type="submit" value="Submit">
</form></body>
</html>


#
# Action for simple form (2) processing with catching particular user input
# Required user input is: John Doe
#
POST /action_page2.php HTTP/1.1

fname=John&lname=Doe

HTTP/1.1 200 OK
Content-Type: text/html
X-Body-Type: text/template

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Form Example</title>
</head>
<body>
	<h1>Hello, ${fname[0]} ${lname[0]}</h1>
</body>
</html>
```

**Comment by xnbox** [comment]
v1.0.9 with bug fixes has been released.
Thank you very much!

**Comment by mjablecnik** [comment]
I copied the same your file and I see that it have also blank lines in bottom of the response:

![image](https://user-images.githubusercontent.com/2686906/133254599-cba5c4e1-1c9f-4ffd-b0ed-cb6b24fa4e22.png)

(there are 2 lines)
So what can I made for remove it from there? :)

**Comment by xnbox** [comment]
- The v1.0.9 release fixes a bug with an extra blank line.
- Two empty lines in the response, because my dump does have two empty lines at the end of the body.
- The CLI option to preserve empty lines has not yet been implemented, so for now they are preserved by default.
- I hope to add this option soon and the problem with empty lines will disappear by itself.

**Comment by xnbox** [comment]
v1.0.10 has been released.
- New option: --no-trim (disable whitespace trimming at the end of the body)

Thank you!

**Comment by mjablecnik** [comment]
Great :+1:  Thank you very much I will try it ;-)

**Comment by mjablecnik** [comment]
So I tested it and it works but when trim is enabled so response have some ugly character on end of body:
![image](https://user-images.githubusercontent.com/2686906/133279895-56658471-5c5f-49c2-88a8-0c569413347d.png)

and I dont know what is it.

The character is there only when trim is enabled when it is disabled so it is not there.

**Comment by mjablecnik** [comment]
But when I have this file: 
![image](https://user-images.githubusercontent.com/2686906/133280376-83e7b008-b389-4f23-a781-16870a6d8a83.png)

So the character is there also when trim is disabled.

**Comment by xnbox** [comment]
I've been testing.
I do not have this symbol.
Can you send me your dump as an attachment to your comment?

**Comment by xnbox** [comment]
Are you using the ZSH shell to run curl?

**Comment by mjablecnik** [comment]
Yes I am using ZSH.
Here is my result with bash:
![image](https://user-images.githubusercontent.com/2686906/133302796-d977e7bf-08ae-4969-98f2-3cfd070eef9e.png)

**Comment by xnbox** [comment]
OK, I get it. This is a feature of the ZSH. It highlights a line which does not have an end of line (EOL) character. This just shows that the fake server is working correctly, because there is no such a symbol in the dump, so the dump is sent to the client accurately. This is good!

**Comment by mjablecnik** [comment]
Ok so when I have:
```
#-----

GET /dapi/v1/user HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json

{
    "firstName": "Martin",
    "id": 67,
    "lastName": "Jablecnik",
    "username": "ML7920161687"
}
#-----
GET /dapi/v1/user/error HTTP/1.1

HTTP/1.1 403 OK
Content-Type: application/json

{
    "args": [
        "16e9a3583dbd01d7fca1a3db62d2fe"
    ],
    "key": "Unknown device %s",
    "message": "Unknown device 16e9a3583dbd01d7fca1a3db62d2fe"
}

#-----

POST /dapi/v1/device/register HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json

#-----
```
And trimming is disabled, I have this:
![image](https://user-images.githubusercontent.com/2686906/133329250-06250c45-d57a-485e-ae33-b40bd3553220.png)

And when I have:
```
#-----

GET /dapi/v1/user HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json

{
    "firstName": "Martin",
    "id": 67,
    "lastName": "Jablecnik",
    "username": "ML7920161687"
}
#-----

GET /dapi/v1/user/error HTTP/1.1

HTTP/1.1 403 OK
Content-Type: application/json

{
    "args": [
        "16e9a3583dbd01d7fca1a3db62d2fe"
    ],
    "key": "Unknown device %s",
    "message": "Unknown device 16e9a3583dbd01d7fca1a3db62d2fe"
}

#-----

POST /dapi/v1/device/register HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json

#-----
```
And trimming is disabled, I have this:
![image](https://user-images.githubusercontent.com/2686906/133329395-e4dbd7ba-4dce-4d68-a33f-a694a7ac0d09.png)

So it is correct behavior?

**Comment by xnbox** [comment]
I'm confused... You have in both cases written "disabled".
As I can see:
First case: without "--no-trim" flag (EOL character removed)
Second case: with "--no-trim" flag (EOL character is preserved)
It is correct behavior.

**Comment by mjablecnik** [comment]
I am also confused because both previous cases which I mentioned are with "--no-trim" flag.

I recorded simple video for better understand.
Before start you can see that I start it with "--no-trim" flag without changing it:

https://user-images.githubusercontent.com/2686906/133341288-2eaf06a5-d19a-4ca1-8345-7f4da9740e89.mp4

So how is EOL character removed when I didn't enable trim?
I only removed blank lines between endpoints. And when there is one line with EOL so response is good but when there is nothing line so there is the character showed.
I think that when trim is enabled so there should be still one EOL between endpoints for nice show of response after request.

**Comment by xnbox** [comment]
Oh! I see! It's a bug!
Sorry for the misunderstanding!

**Comment by xnbox** [comment]
I figured it out. You have to somehow know where the body ends up. If we know where the body ends, we can use empty lines and comments after the body. We don't want to change the original body.

```
GET /dapi/v1/user1 HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json

{
    "firstName": "Martin",
    { "id": 11,
    { "lastName": "Jablecnik",
    { "username": "ML7920161687"
}
.
# Some comments...
```

A dot (.) is used as a sign of the end of the body.
If there is no dot, the sign of the end of body will be the beginning of the next request/response or the end of the dump file.
So if you need comments - use a dot.

**Comment by mjablecnik** [comment]
Ok I will try it when it will be released :+1:

**Comment by mjablecnik** [comment]
So the trim functionality can be also removed right now when the body can be ended by the dot character. Or not?

**Comment by xnbox** [comment]
OK, remove the "--no-trim" option, because with a point the user can control trimming.

**Comment by xnbox** [comment]
with a dot(.)

**Comment by xnbox** [comment]
v1.0.11 (with dot(.) support) released

**Comment by mjablecnik** [comment]
I tried the latest version right now but I see that comments are not working inside of response body right now..

**Comment by xnbox** [comment]
The correct behavior is not to change the original body of the request/response defined in the dump.

**Comment by xnbox** [comment]
I just thought that for your purposes
would work fine <code>X-Body-Type: text/template</code>
See example:

```
#
# Comments example
#
GET /customer2.json HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json
X-Body-Type: text/template

<#-- Put your comments anywhere on body -->
<#-- Customer record -->
{
    "id": 123,
    "fname": "John", <#-- First Name -->
    "lname": <#-- ...even here --> "Doe",
    "email": ["john@example.com", "johndoe@example.com"]
}
<#-- ...and here -->
.
```

**Comment by mjablecnik** [comment]
Ok I will try it.
