### ISSUE TITLE
Configurable log verbose

### ISSUE THREAD

**Issue by mjablecnik** [xnbox/DeepfakeHTTP#7]
Exists some possibility how to show in stdout only one line requests and more detailed information about request/response move into some special log file? Or show it only with -v, -vv, -vvv verbose tags.
I think there is too a lot of information in stdout per every request for now but I don't want to disable it..

**Comment by xnbox** [comment]
Great proposal!
Put it on my TODO list!
Thank you!

**Comment by xnbox** [comment]
Done.
Options:
   --max-log-body <number> (max body bytes in console log, default: unlimited)
   --no-log (disable request/response console logging)
   --no-log-headers (disable request/response headers in console logging)
   --no-log-body (disable request/response body in console logging)
