### ISSUE TITLE
Missing new --no-redirect tag in help

### ISSUE THREAD

**Issue by mjablecnik** [xnbox/DeepfakeHTTP#8]
I see that in your latest version you have new `--no-redirect` cli tag:
![image](https://user-images.githubusercontent.com/2686906/133207927-dcad8d0e-70d0-4825-b719-d8e2ded53f13.png)

but in help it is missing:

![image](https://user-images.githubusercontent.com/2686906/133207654-09dfc91e-5906-4067-b924-a9d93c13d3f6.png)

There is only `--redirect` tag.

**Comment by xnbox** [comment]
This is a bug in the release comment. Instead of "--no-redirect" you need: "--redirect".
I fixed the comment to the release.
Thank you!
