### ISSUE TITLE
Options are detected as files

### ISSUE THREAD

**Issue by mjablecnik** [xnbox/DeepfakeHTTP#9]
When I run command:
```
java -jar ~/Downloads/df-1.0.8.jar --port 3000 /home/martin/Projects/my-project/endpoints/*
```

So Deepfake detect argument `--port 3000` as file inputs:
![image](https://user-images.githubusercontent.com/2686906/133209195-f79ac2c0-c339-4e92-8727-8223e48c3861.png)

**Comment by xnbox** [comment]
Confirm bug. Fix required.
Thank you!

**Comment by xnbox** [comment]
Fixed
